# Generated by Django 3.1.4 on 2021-02-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('state', models.CharField(choices=[('UNINITIATED', 'UNINITIATED'), ('IN PROCESS', 'IN PROCESS'), ('READY', 'READY')], max_length=100)),
            ],
        ),
    ]
